name:                mesos-client
version:             0.1.0.0
github:              "schernichkin/mesos-client"
license:             BSD3
author:              "Stanislav Chernichkin"
maintainer:          "schernichkin@gmail.com"
copyright:           "Copyright (C) 2017 Stanislav Chernichkin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schernichkin/mesos-client#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- bytestring
- conduit
- conduit-extra
- exceptions
- fclabels
- http-client
- http-conduit
- http-types
- mesos-protos
- protocol-buffers
- protocol-buffers-descriptor
- singletons
- transformers
- unliftio

library:
  source-dirs: src

executables:
  mesos-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - mesos-client

tests:
  mesos-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mesos-client
